# Generated by Django 5.1.2 on 2024-10-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('class_div', models.CharField(max_length=5)),
            ],
        ),
    ]
